artipie/maven-adapter

src/main/java/com/artipie/maven/ArtifactCoordinates.java, src/main/java/com/artipie/maven/FileCoordinates.java, src/main/java/com/artipie/maven/Repository.java, src/main/java/com/artipie/maven/aether/AetherRepository.java, src/main/java/com/artipie/maven/aether/LocalArtifactResolver.java, src/main/java/com/artipie/maven/aether/LocalResolver.java, src/main/java/com/artipie/maven/aether/ServiceLocatorFactory.java
`AetherRepository` starts Maven library deployment lifecycle using `org.eclipse.aether.RepositorySystem.deploy()` method
=> #10: AetherRepository

src/main/java/com/artipie/maven/aether/AetherRepository.java, src/main/java/com/artipie/maven/aether/AstoTransporter.java, src/main/java/com/artipie/maven/aether/ServiceLocatorFactory.java, src/test/java/com/artipie/maven/aether/AetherRepositoryTest.java, src/test/java/com/artipie/maven/aether/ServiceLocatorFactoryTest.java
issue #32
Makes `AetherRepository#upload` work.
=> #32: AetherRepositoryTest

src/test/resources/logback.xml
=> #47: configure logging

src/main/java/com/artipie/maven/metadata/Metadata.java, src/main/java/com/artipie/maven/metadata/package-info.java, src/test/java/com/artipie/maven/metadata/MetadataMavenTest.java, src/test/java/com/artipie/maven/metadata/package-info.java
For #57 :
- Added `Metadata.Maven` test for correct generation
- Changed puzzle to implement correct method
=> For #57: Implementation of Metadata.Maven

src/main/java/com/artipie/maven/file/File.java, src/main/java/com/artipie/maven/file/checksum/Md5.java, src/main/java/com/artipie/maven/file/checksum/Sha1.java, src/test/java/com/artipie/maven/file/AstoFileTest.java, src/test/java/com/artipie/maven/file/package-info.java, src/test/java/com/artipie/maven/metadata/MetadataMavenTest.java
For #58:
- Created `File.Asto` skeleton implementation
- Created tests for `File.Asto`
- Left puzzle for implementing the actual class
=> For #58: created File.Asto implementation and tests

pom.xml, src/main/java/com/artipie/maven/metadata/Metadata.java, src/test/java/com/artipie/maven/metadata/MetadataMavenTest.java
For #60 
-  implemented metadata generation
- enabled test
=> For #60: implementation of metadata generation

src/main/java/com/artipie/maven/file/File.java, src/test/java/com/artipie/maven/file/AstoFileTest.java
=> Implements maven adapter File

README.md
=> Add result of investigation on the needed HTTP APIs

src/test/java/com/artipie/maven/file/AstoFileTest.java
For #70: Fixed tests in AstoFileTest to wait for completable execution before going on.
=> For #70: fixing AstoFileTest

README.md
For #66: README.md update on Maven class behavior
=> For #66: README.md update on Maven class behavior

README.md, pom.xml, src/test/java/com/artipie/maven/MavenHttpITCase.java, src/test/java/com/artipie/maven/MavenITCase.java
=> Add MavenITCase to start working on the HTTP API

pom.xml, src/main/java/com/artipie/maven/http/MavenSlice.java
#79 The only auth type for maven is basic.
=> Basic auth for maven

README.md, pom.xml, src/main/java/com/artipie/maven/http/MavenSlice.java, src/test/java/com/artipie/maven/MavenHttpITCase.java
=> (#72) Support upload of artifacts via maven client

src/main/java/com/artipie/maven/http/MavenSlice.java
=> Added Auth for upload API

src/main/java/com/artipie/maven/http/DownloadMavenSlice.java, src/main/java/com/artipie/maven/http/MavenProxySlice.java, src/main/java/com/artipie/maven/http/MavenSlice.java, src/main/java/com/artipie/maven/http/RepositorySlice.java, src/main/java/com/artipie/maven/repository/Repository.java, src/main/java/com/artipie/maven/repository/RpLocal.java, src/main/java/com/artipie/maven/repository/RpRemote.java, src/main/java/com/artipie/maven/repository/package-info.java
This is for #92. @g4s8 FYI, there are a lot of todos :)
=> (#92) - First step toward Maven Proxy

src/main/java/com/artipie/maven/Maven.java, src/test/java/com/artipie/maven/MavenTest.java
For #91: Added checksum generation tests
- added checksum generation tests
- left puzzle to continue
=> For #91: added checksum tests

src/main/java/com/artipie/maven/repository/ProxyCache.java, src/main/java/com/artipie/maven/repository/Repository.java, src/main/java/com/artipie/maven/repository/RpRemote.java, src/main/java/com/artipie/maven/repository/StorageCache.java, src/test/java/com/artipie/maven/repository/StorageCacheTest.java, src/test/java/com/artipie/maven/repository/package-info.java
#98 - added cache interface and `Storage` implementation for remote Maven proxy.
=> Maven proxy cache

pom.xml, src/main/java/com/artipie/maven/MavenMetadata.java, src/main/java/com/artipie/maven/repository/StorageCache.java, src/test/java/com/artipie/maven/MavenHttpITCase.java, src/test/java/com/artipie/maven/repository/StorageCacheTest.java
#105 - fixed maven cache - save data to cache first, asked SO question https://stackoverflow.com/q/62405268/1723695
=> Fixed Maven proxy cache

README.md, pom.xml
For #107:
- added codecov badge to readme
- fixed jacoco execution in pom
=> For #107: jacoco and codecov configuration

README.md
For #81: 
- added snapshot repositories info to readme
- left puzzle for implementation
=> For #81: added snapshot repositories info to readme

src/main/java/com/artipie/maven/repository/RpRemote.java
#114 - use callback after chunks reading, see https://github.com/jetty-project/jetty-reactive-httpclient#example-discarding-non-200-ok-response-content
@artipie/contributors you may need similar fix for other proxies
=> Use callback after chunks reading

.github/workflows/release.yml, pom.xml
#114 - updated parent pom and added workflow file to deploy to central.artipie.com
=> Deploy to artipie central

pom.xml, src/main/java/com/artipie/maven/repository/RepositoryChecksums.java, src/test/java/com/artipie/maven/http/package-info.java, src/test/java/com/artipie/maven/repository/RepositoryChecksumsTest.java
#117 - added `RepositoryChecksums` to read checksum files to add values to response headers then.
=> Repository checksums

.github/workflows/ci-checks.yml, .github/workflows/release.yml, pom.xml, src/main/java/com/artipie/maven/http/ArtifactGetResponse.java, src/main/java/com/artipie/maven/http/ArtifactHeadResponse.java, src/main/java/com/artipie/maven/http/ArtifactHeaders.java, src/test/java/com/artipie/maven/http/ArtifactGetResponseTest.java, src/test/java/com/artipie/maven/http/ArtifactHeadResponseTest.java, src/test/java/com/artipie/maven/http/ArtifactHeadersTest.java
#117 - introduced `GET` and `HEAD` responses with artifact headers.
=> GET and HEAD responses with headers

src/main/java/com/artipie/maven/http/LocalMavenSlice.java, src/main/java/com/artipie/maven/http/MavenProxySlice.java, src/main/java/com/artipie/maven/http/MavenSlice.java, src/main/java/com/artipie/maven/http/RemoteDownloadSlice.java
#117 - support `HEAD` requests, added artifact headers to responses.
=> Respond with artifact headers

src/main/java/com/artipie/maven/repository/RepositoryChecksums.java, src/test/java/com/artipie/maven/repository/RepositoryChecksumsTest.java, src/test/java/com/artipie/maven/repository/ValidUploadAstoTest.java
For #132 added method to generate checksums to `RepositoryChecksums`.
=> #132 - added method to generate checksums to RepositoryChecksums

pom.xml, src/main/java/com/artipie/maven/http/MavenProxySlice.java
#128 - integrated HTTP client to proxy Maven slice
=> Integrated HTTP client

pom.xml, src/main/java/com/artipie/maven/http/UpdateMavenSlice.java
=> #122 - update http and use ContentWithSize

src/test/java/com/artipie/maven/AstoMavenITCase.java, src/test/java/com/artipie/maven/MetadataXml.java, src/test/java/com/artipie/maven/asto/AstoValidUploadTest.java, src/test/java/com/artipie/maven/metadata/ArtifactsMetadataTest.java
For #151 I've introduced `MetadataXml` class to generate and add maven metadata to storage.
=> #151 - MetadataXml introduced

src/main/java/com/artipie/maven/asto/AstoValidUpload.java, src/test/java/com/artipie/maven/asto/AstoValidUploadTest.java
For #143 refactored `AstoValidUploadTest` to avoid code duplications
=> #143 - remove code duplications from AstoValidUploadTest

pom.xml, src/main/java/com/artipie/maven/http/MavenSlice.java, src/test/java/com/artipie/maven/MavenITCase.java, src/test/resources-binary/helloworld-src/README.md, src/test/resources-binary/helloworld-src/pom.xml, src/test/resources-binary/helloworld-src/src/main/java/com/artipie/helloworld/HelloWorld.java
Part of #137 - test with auth and for deploy.
=> #137 - added tests with auth and deploy

pom.xml, src/test/java/com/artipie/maven/MavenITCase.java
For #168 - updated asto and used new method from `TestResource`.
=> #168 - updated asto

pom.xml, src/main/java/com/artipie/maven/http/UpdateMavenSlice.java, src/test/java/com/artipie/maven/http/UpdateMavenSliceTest.java
Closes #178 
Using exclusive storage access on metadata copy
=> #178 - Using exclusive storage access on metadata copy

src/test/resources-binary/com/artipie/helloworld/maven-metadata.xml
Closes #191 
Fixed invalid XML to comply with XCOP check
=> #191 - Fixed invalid XML to comply with XCOP check

pom.xml, src/main/java/com/artipie/maven/http/MavenProxySlice.java, src/main/java/com/artipie/maven/http/MavenSlice.java
Bumped http version to 0.16.1 and made necessary corrections.
=> Update http to 0.16.1

pom.xml, src/test/java/com/artipie/maven/http/MavenProxySliceITCase.java
Part of #197 
Created IT case to verify that `MavenProxySlice` can work with maven central.
=> #197 - proxy central test

src/main/java/com/artipie/maven/http/CachedProxySlice.java, src/main/java/com/artipie/maven/http/MavenProxySlice.java, src/main/java/com/artipie/maven/http/RepoHead.java, src/test/java/com/artipie/maven/http/MavenProxySliceITCase.java, src/test/java/com/artipie/maven/http/RepoHeadITCase.java
Part of #197 
I've fixed and tested `RepoHead`, added IT case with vert.x for `MavenProxySlice` and also fixed it.
=> #197 - fixed and tested RepoHead and MavenProxySlice

src/test/java/com/artipie/maven/MavenProxyIT.java
Part of #197 
Add `MavenProxyITCase`. Verify that artifact was downloaded from repo and saved in the storage.
=> #197 - Add MavenProxyITCase

pom.xml, src/main/java/com/artipie/maven/http/MavenProxySlice.java, src/test/java/com/artipie/maven/MavenProxyIT.java
Closes #138 
Using `UriClientSlice` in proxy
=> #138 - Using UriClientSlice in proxy

pom.xml, src/main/java/com/artipie/maven/http/MavenProxySlice.java, src/test/java/com/artipie/maven/MavenProxyIT.java, src/test/java/com/artipie/maven/http/MavenProxySliceAuthIT.java
Closes #204 
Authentication support in proxy
=> #204 - Authentication support in proxy

src/main/java/com/artipie/maven/http/HeadProxySlice.java, src/test/java/com/artipie/maven/http/MavenProxySliceITCase.java
Part #212 
I've fixed `HeadProxySlice` do not pass headers on request to proxy and return obtained headers from proxy to the client.
=> #212 - HeadProxySlice fixed

src/test/java/com/artipie/maven/http/HeadProxySliceTest.java
Closes #212 
Added unit test for `HeadProxySlice`
=> #212 - HeadProxySlice unit test

src/main/java/com/artipie/maven/http/CachedProxySlice.java, src/test/java/com/artipie/maven/http/MavenProxySliceITCase.java
Closes #219 
Fix `MavenProxySlice` response when not found
=> #219 - Fix MavenProxySlice response

src/main/java/com/artipie/maven/http/UploadSlice.java, src/test/java/com/artipie/maven/http/UploadSliceTest.java
Part of #227 
Implemented `UploadSlice` and added test for the class.
=> Implemented `UploadSlice`

src/main/java/com/artipie/maven/http/PutMetadataChecksumSlice.java, src/test/java/com/artipie/maven/http/PutMetadataChecksumSliceTest.java
Part of #227 
Implemented part of `PutMetadataChecksumSlice` job to pick suitable `maven-metadata.xml` and save checksum to the correct location. Added corresponding tests.
=> Partly implemented `PutMetadataChecksumSlice`

src/main/java/com/artipie/maven/http/PutMetadataSlice.java, src/main/java/com/artipie/maven/http/UpdateMavenSlice.java, src/main/java/com/artipie/maven/metadata/DeployMetadata.java, src/test/java/com/artipie/maven/http/PutMetadataSliceTest.java, src/test/java/com/artipie/maven/metadata/DeployMetadataTest.java
Part of #227 
Implemented `PutMetadataSlice` and added tests for it. Also, made `DeployMetadata` synchronous, it's more convenient this way.
=> Implemented `PutMetadataSlice`

src/main/java/com/artipie/maven/ValidUpload.java, src/main/java/com/artipie/maven/http/PutMetadataChecksumSlice.java, src/test/java/com/artipie/maven/http/PutMetadataChecksumSliceTest.java
Part of #227 
Added upload validation and started repository update in `PutMetadataChecksumSlice`
=> Added validation and started update in `PutMetadataChecksumSlice`

README.md
Closes #227 
Extended readme with update process info.
=> Update readme with update process info
