artipie/maven-adapter

- src/test/java/com/artipie/maven/test/OptionalAssertions.java
- src/test/java/com/artipie/maven/test/OptionalAssertionsTest.java
[#7: OptionalAssertionsTest](https://github.com/artipie/maven-adapter/issues/7)
Class `com.artipie.maven.test.OptionalAssertions` provides helpful assertions for `java.util.Optional` but it requires unit testing too.
> #7: OptionalAssertionsTest

- src/main/java/com/artipie/maven/aether/LocalArtifactResolver.java
- src/test/java/com/artipie/maven/aether/LocalArtifactResolverTest.java
From #20 :
`LocalArtifactResolver` resolves an artifact in a local repository by its relative path.
The class was not covered by test to split the original pull request.
> #20: LocalArtifactResolverTest

- src/main/java/com/artipie/maven/aether/ServiceLocatorException.java
- src/main/java/com/artipie/maven/aether/ServiceLocatorFactory.java
- src/main/java/com/artipie/maven/aether/ValidatingServiceLocator.java
- src/test/java/com/artipie/maven/aether/ValidatingServiceLocatorTest.java
From #22:
`org.eclipse.aether.spi.locator.ServiceLocator` is a ServiceLocator pattern interface. It creates/retrieves services by matching service class. If the service was not yet registered it simply returns null forcing you to make a null check on each invocation.
We should hide null checks in another class implementing the interface.
> #22: ValidatingServiceLocator

- src/main/java/com/artipie/maven/FileCoordinates.java
- src/test/java/com/artipie/maven/FileCoordinatesTest.java
From #24 :
`FileCoordinates` contains two methods: `coords()` and `path()` that throw `UnsupportedOperationException`. We should implement it (and unit test too).
The class was not implemented to split the original pull request.
> #24: implement FileCoordinates coords() and path()

- src/main/java/com/artipie/maven/aether/AstoTransporter.java
- src/main/java/com/artipie/maven/aether/AstoTransporterFactory.java
- src/main/java/com/artipie/maven/aether/ResourceNotFoundException.java
- src/test/java/com/artipie/maven/aether/AstoTransporterFactoryTest.java
- src/test/java/com/artipie/maven/aether/AstoTransporterTest.java
issue #28 
Asto integration is done by implementing interfaces
`org.eclipse.aether.spi.connector.transport.TransporterFactory` and  `org.eclipse.aether.spi.connector.transport.Transporter` laying deeply in Maven services.
These services will be registered in a Service Locator in `com.artipie.maven.aether.ServiceLocatorFactory` and actual class usage will be introduced in `com.artipie.maven.aether.AetherRepository` in following pull requests.
> #28: Asto integration

- src/main/java/com/artipie/maven/ChecksumAttribute.java
- src/test/java/com/artipie/maven/ChecksumAttributeTest.java
issue #35 
- writing checksums is no longer required, Maven library does it for you;
- reading checksums from checksum files, now it calculates directly from an artifact;
- migrate a unit test from JUnit assertions to Hamcrest assertions.
> #35: read checksum attribute file

- pom.xml
- src/main/java/com/artipie/maven/aether/AstoTransporter.java
- src/main/java/com/artipie/maven/aether/repository/AetherRepository.java
- src/main/java/com/artipie/maven/aether/repository/Deployer.java
- src/test/java/com/artipie/maven/aether/repository/DeployerTest.java
- src/test/java/com/artipie/maven/aether/repository/package-info.java
issue #36 BTW reactive approach makes uploading lifecycle clearer.
`Deployer` class javadoc has a qulice suppression, explained in `AetherRepository`.
> #36: Repository upload with reactive interface

- pom.xml
- src/main/java/com/artipie/maven/http/DownloadMavenSlice.java
- src/main/java/com/artipie/maven/repository/ArtifactNotFoundException.java
- src/main/java/com/artipie/maven/repository/Repository.java
- src/main/java/com/artipie/maven/repository/RpLocal.java
- src/main/java/com/artipie/maven/repository/RpRemote.java
#96 - returns `Content` from `Repository` instead of `Response`. Moved HTTP logic to `Slice` level.
> Repository returns content instead of response

- src/main/java/com/artipie/maven/Maven.java
- src/main/java/com/artipie/maven/http/UpdateMavenSlice.java
- src/main/java/com/artipie/maven/repository/ValidUpload.java
- src/test/java/com/artipie/maven/http/UpdateMavenSliceTest.java
Part of #113 
- introduced `ValidUpload` abstraction and `Dummy` implementation
- used this new abstraction in `UpdateMavenSlice`
- created test for `UpdateMavenSlice`
- added todos to continue
> #113 - introduced ValidUpload abstraction

- src/main/java/com/artipie/maven/AstoMaven.java
- src/main/java/com/artipie/maven/Maven.java
- src/main/java/com/artipie/maven/http/UpdateMavenSlice.java
- src/test/java/com/artipie/maven/AstoMavenITCase.java
- src/test/java/com/artipie/maven/AstoMavenTest.java
- src/test/java/com/artipie/maven/http/UpdateMavenSliceTest.java
For #124 I've extracted interface from `Maven`, renamed `Maven` to `AstoMaven` and extended `UpdateMavenSliceTest` to verify that `Maven#update` is called.
> #124 - extract interface from `Maven`

- src/main/java/com/artipie/maven/http/UpdateMavenSlice.java
- src/test/java/com/artipie/maven/http/UpdateMavenSliceTest.java
Part of #113. 
`UpdateMavenSlice` now uploads files to temp location and then after `maven-metadata.xml` is received and upload is validated copies them to permanent location.
> #113 - upload files to temp location

- src/main/java/com/artipie/maven/ValidUpload.java
- src/main/java/com/artipie/maven/asto/AstoValidUpload.java
- src/main/java/com/artipie/maven/http/UpdateMavenSlice.java
- src/main/java/com/artipie/maven/metadata/ArtifactsMetadata.java
- src/test/java/com/artipie/maven/asto/AstoValidUploadTest.java
- src/test/java/com/artipie/maven/metadata/ArtifactsMetadataTest.java
For #131 validate `maven-metadata.xml` and set up validation process. Validation process now includes:
- check artifact and group ids in uploaded and existing `maven-metadata.xml`
- check uploaded `maven-metadata.xml` checksums (if there are any)
- check that artifacts with version specified in `maven-metadata.xml` exists (are uploaded) and their checksums are valid
> #131 - upload validation process

- src/main/java/com/artipie/maven/Maven.java
- src/main/java/com/artipie/maven/ValidUpload.java
- src/main/java/com/artipie/maven/asto/AstoMaven.java
- src/main/java/com/artipie/maven/asto/AstoValidUpload.java
- src/main/java/com/artipie/maven/http/UpdateMavenSlice.java
- src/main/java/com/artipie/maven/metadata/ArtifactsMetadata.java
- src/test/java/com/artipie/maven/AstoMavenITCase.java
- src/test/java/com/artipie/maven/AstoMavenTest.java
- src/test/java/com/artipie/maven/metadata/ArtifactsMetadataTest.java
- src/test/resources-binary/com/artipie/asto/maven-metadata.xml
Closes #113, now all files are uploaded to the temp location, validated, metadata generated and copied to permanent location. Changes:
- `AstoMaven` generates `maven-metadata.xml` to temp location, uploaded version is read from uploaded `maven-metadata.xml`
- `ArtifactsMetadata` reads `release` version from `maven-metadata.xml` as uploaded `maven-metadata.xml` not necessarily contains `latest` tag, xml for the new artifact looks like this
```
<?xml version="1.0" encoding="UTF-8"?>
<metadata>
<groupId>org.apache.maven.resolver</groupId>
<artifactId>maven-resolver-util</artifactId>
<versioning>
<release>1.3.3</release>
<versions>
<version>1.3.3</version>
</versions>
<lastUpdated>20200817054301</lastUpdated>
</versioning>
</metadata>
``` 
- `AstoValidUpload` works properly with new artifact …
> #113 - Maven upload validation enabled

- src/test/java/com/artipie/maven/MavenHttpITCase.java
- src/test/java/com/artipie/maven/http/UpdateMavenSliceTest.java
Closes #144 
Added test to `UpdateMavenSliceTest` to verify that update is not start when snapshot metadata file is sent.
Extended `MavenHttpITCase` to verify proper deployment with snapshot versions.
> #144 - do not start update on snapshot upload

- src/main/java/com/artipie/maven/http/UpdateMavenSlice.java
Closes #189 
Extended locking scope in `UpdateMavenSlice`, so there will be no race condition for `.upload` folder which is shared for multiple uploads.
> #189 - Extended locking scope in UpdateMavenSlice

- src/main/java/com/artipie/maven/ValidUpload.java
- src/main/java/com/artipie/maven/asto/AstoValidUpload.java
- src/test/java/com/artipie/maven/asto/AstoValidUploadTest.java
Part of #227 
Extended `ValidUpload` with `ready()` method to check whether the upload is ready to be added to the repository
> Extended `ValidUpload` with `ready()` method

- src/main/java/com/artipie/maven/asto/AstoMavenWithMove.java
- src/test/java/com/artipie/maven/asto/AstoMavenWithMoveTest.java
- src/test/resources-binary/com/artipie/asto/0.20.2/asto-0.20.2.jar.lastUpdated
- src/test/resources-binary/com/artipie/asto/0.20.2/asto-0.20.2.pom.lastUpdated
Part of #227 
Added new `Maven` implementation: this implementation locks repository package and moves all the files to the right location after update is done. Will use this class in `PutMetadataChecksumSlice`, `AstoMaven` will be removed leter.
> Added new `Maven` implementation

- src/main/java/com/artipie/maven/asto/AstoMaven.java
- src/main/java/com/artipie/maven/asto/AstoValidUpload.java
- src/main/java/com/artipie/maven/http/MavenSlice.java
- src/main/java/com/artipie/maven/http/PutMetadataChecksumSlice.java
- src/main/java/com/artipie/maven/http/PutMetadataSlice.java
- src/test/java/com/artipie/maven/MavenITCase.java
- src/test/java/com/artipie/maven/asto/AstoMavenTest.java
- src/test/java/com/artipie/maven/asto/AstoValidUploadTest.java
- src/test/java/com/artipie/maven/http/PutMetadataChecksumSliceTest.java
- src/test/java/com/artipie/maven/http/PutMetadataSliceTest.java
Part of #227 
Snapshot versions have their own metadata files, which maven uploads after all artifacts and before package metadata by path
```
PUT /com/artipie/asto/1.0-SNAPSHOT/maven-metadata.xml
```
This path coincides with the path we store package upload metadata, to avoid the problem I've made adapter to store package metadata into separate subdir (or sub-key) `meta`.
Snapshot metadata should not be processed, simply copied to local repository.
> Put metadata by separate sub-key (directory)

- src/main/java/com/artipie/maven/asto/AstoMaven.java
- src/main/java/com/artipie/maven/asto/AstoValidUpload.java
- src/main/java/com/artipie/maven/http/PutMetadataSlice.java
- src/main/java/com/artipie/maven/metadata/DeployMetadata.java
- src/test/java/com/artipie/maven/MavenITCase.java
- src/test/java/com/artipie/maven/asto/AstoMavenTest.java
- src/test/java/com/artipie/maven/http/PutMetadataSliceTest.java
- src/test/java/com/artipie/maven/metadata/DeployMetadataTest.java
Part of #227 
Implemented choosing upload version on maven metadata upload: we first try to find suitable uploading snapshot, if there is not any, save metadata by release version. Also fixed several other problems:
- moving files to the repository after the update in `AstoMaven` and its test (because of the mistake in the test bug in `AstoMaven`) was not visible
- `AstoValidUpload` should check package metadata from the `meta` sub-key
- extended `DeployMetadata` with method to read snapshot versions
- enabled `deploysSnapshot` in `MavenITCase`
> Choose upload version when package metadata are uploaded

- src/main/java/com/artipie/maven/http/PutMetadataSlice.java
- src/test/java/com/artipie/maven/MavenITCase.java
- src/test/java/com/artipie/maven/http/PutMetadataSliceTest.java
Closes #242 
Fixed `PutMetadataSlice` to handle snapshots only artifacts properly: when package has only snapshot versions there is no `release` tag in maven metadata and we should not try to obtain it.
> Snapshots only artifacts
